#!/usr/bin/env bash
set -eu
set -o pipefail

CWD=$(pwd)
TMP_DIR="${CWD}"/tmp
OUTPUT_DIR="${CWD}"/output
GPG_HOME_DIR="${OUTPUT_DIR}"/gpg_home
GPG_BATCH_FILE=""
NAME="testuser"
EMAIL="testuser@email.com"
EXPIRE_DATE="0"
PASSPHRASE="test123"

print_help()
{
    echo "usage: make_gpg_keys [-h] -b -c -d -e -n -o -p -x"
    echo ""
    echo "options:"
    echo "-h, --help              Show this help message and exit."
    echo "-b, --gpg-batch-file    GPG batch file location. If unspecified, one will be generated automatically."
    echo "-d, --gpg-home-dir      GPG home directory location. Must not be ${HOME}/.gnupg"
    echo "-e, --email             GPG key email address/"
    echo "-n, --name              Name used for the GPG key."
    echo "-o, --output            Output directory for the armored GPG key, key secret, and key passphrase."
    echo "-p, --passphrase        GPG key passphrase."
    echo "-x, --expire-date       GPG key expiration date."
    echo ""
    exit 0
}

parse_args() {
  local o O opts
  o='hb:d:e:n:o:p:x:'
  O='help,gpg-batch-file:,email:,gpg-home-dir:,name:,output:,passphrase:,expire-date:'
  opts="$(getopt -o "${o}" -l "${O}" -- "${@}")"
  eval set -- "${opts}"

  while [[ ${#} -gt 0 ]]; do
    case "${1}" in
    (-h|--help)
      print_help
      ;;
    (-b|--gpg-batch-file)
      GPG_BATCH_FILE="${2}"
      shift 2
      ;;
    (-d|--gpg-home-dir)
      GPG_HOME_DIR="${2}"
      shift 2
      ;;
    (-e|--email)
      EMAIL="${2}"
      shift 2
      ;;
    (-n|--name)
      NAME="${2}"
      shift 2
      ;;
    (-o|--output)
      OUTPUT_DIR="${2}"
      shift 2
      ;;
    (-p|--passphrase:)
      PASSPHRASE="${2}"
      shift 2
      ;;
    (-x|--expire-date)
      EXPIRE_DATE="${2}"
      shift 2
      ;;
    (--)
        shift; break
        ;;
    *)
      print_help
    esac
  done

  if [[ "${OUTPUT_DIR}" == "${HOME}"/.gnupg ]]; then
    echo "The output directory must not be ${HOME}/.gnupg!"
    exit 1
  fi
}

gen_batch_file() {
  local batch_comment="RPM ${1} GPG Keys"
  GPG_BATCH_FILE="${GPG_BATCH_FILE:-${TMP_DIR}/gpg.batch}"
  mkdir -p "${TMP_DIR}"

  if [[ ! -e "${GPG_BATCH_FILE}" ]]; then

cat <<- EOF > "${GPG_BATCH_FILE}"
%echo Generating RPM ${1} GPG Keys
Key-Type: RSA
Key-Length: 4096
Name-Real: ${NAME}
Name-Email: ${EMAIL}
Name-Comment: ${batch_comment}
Expire-Date: ${EXPIRE_DATE}
passphrase: ${PASSPHRASE}
%commit
%echo done
EOF
  fi
}

gen_keys() {
  gpg \
      --batch \
      --gen-key \
      --homedir "${GPG_HOME_DIR}" \
      "${GPG_BATCH_FILE}"

  rm -rf "${TMP_DIR}"
}

export_keys() {
    local export_comment="RPM ${1} GPG Keys"
    local output_dir="${OUTPUT_DIR}"/"${1}"

    gpg_base="gpg \
      --batch \
      --homedir=${GPG_HOME_DIR} \
      --pinentry-mode=loopback \
      --passphrase ${PASSPHRASE} \
      --armor"

    mkdir -p "${output_dir}"
    chmod 0700 "${output_dir}"

    sanity_check="$(gpg --homedir="${GPG_HOME_DIR}" \
      --list-secret-keys | grep "${export_comment}")"

    if [[ -z "${sanity_check}" ]]; then
      echo "Key with comment: ${export_comment} does not exist in ${GPG_HOME_DIR}!"
      exit 1
    fi

    ${gpg_base} \
      --output "${output_dir}"/key.pub \
      --export "${export_comment}"

    ${gpg_base} \
      --output "${output_dir}"/key.secret \
      --export-secret-key "${export_comment}"

    echo "${PASSPHRASE}" > "${output_dir}"/key.passphrase
}

make_rpm_repo_keys() {
  gen_batch_file "repo"
  gen_keys
  export_keys "repo"
}

make_rpm_package_keys() {
  gen_batch_file "packages"
  gen_keys
  export_keys "packages"
}

main() {
    parse_args "${@}"

    mkdir -p "${GPG_HOME_DIR}"
    chmod 0700 "${GPG_HOME_DIR}"
    make_rpm_repo_keys
    make_rpm_package_keys
    echo "Keys are found in ${OUTPUT_DIR}"
}

main "${@}"
